### ISSUE TITLE
[CATEGORYsEARCHvIEW] [REQUIRED] Category and search bar interface

### ISSUE THREAD

**Issue by tar-singh** [FBU-2018-jalvarado/item-share-app#36]

**Comment by tar-singh** [comment]
-

**Comment by Stephanielpt** [comment]
DONE
- ~~if user clicks on category, and it is not the lowest level then a new categorySearchView swipes in from the right with a back button. it shows the subcategories of that supercategory at top and items in tableview change to the items from the supercategory. the searchbar clears.~~
-  ~~items and categories show up if contain substring~~
  - ~~if search string matches categories, categories appear at top, with items matching search string below. ~~
- ~~have [cancel] button to the left of search bar that will drop categorySearchView if pressed~~

**Comment by Stephanielpt** [comment]
DONE
- if user clicks on category and it is the lowest level then it goes to the map and like above, a new categorySearchView swipes in from right with a back button and items in new tableview are those of that category (but user cannot see this happening because the categorySearchView has dropped). if user continues searching, it will only search within the category clicked
  - if search string only matches items, no categories appear and only items matching search string appear
- if user clicks on an item, it shows that singular pin on the map but it also zooms into the pin's location and the categorySearchView drops
- if user only clicks through categories, they keep appearing at top of tableview which fills with items in that category and once they hit the lowest, the categorySearchView goes back down and all items in that lowest category appear on map
- item model has a category key with the value equal to an array of categories organized from super to sub

**Comment by Stephanielpt** [comment]
DONE

- once tapping on category (whether or not searchbar is filled), map filters according to category.
- make category collection go behind table view when not needed
- create real data

**Comment by Stephanielpt** [comment]
WOOOOO finallllllly
